[FEAT]/#16-대학메일 인증
UMC-Umark/umark-server pull request #17
Opened 2024-01-22 08:40 UTC by SIWON990327

UniCert api를 사용하여 대학메일 인증과 로그인 로직을 만들었습니다
-api키는 현재 로컬 properties에 넣은 뒤 ignore 처리해두었습니다
-code까지 인증 시 다음부터는 인증을 할 수 없습니다(1회성)
-메일 발송 및 code 인증 성공시 상태값이 True가 되도록 설정해두었습니다

MemberControllerd의 엔드포인트는 api/member로 설정해두었습니다

2024-01-22 10:56 UTC, yeeunni requested changes

2024-01-22 10:56 UTC, yeeunni commented on src/main/java/umc/project/umark/domain/member/MemberService.java
> +
DB에 접근하는 service라서 '@ Transactional' 쓰면 좋을 것 같습니다.

2024-01-23 04:32 UTC, hig1002 approved these changes

2024-01-23 07:19 UTC, koojun99 requested changes

2024-01-23 07:19 UTC, koojun99 commented on src/main/java/umc/project/umark/domain/member/MemberResponse.java
1. MemberRegistDto -> MemberRegisterDto로 바꾸는 건 어떨까요?
2. Member관련 api 응답의 모음인 것이 더 이해가 잘 되도록 MemberApiResponse 같은 이름으로 클래스명을 바꾸는 건 어떤지?

2024-01-23 07:19 UTC, koojun99 commented on src/main/java/umc/project/umark/global/exception/ApiResponse.java
저희가 사전에 이야기한 api 응답 양식으로 일부 수정이 필요한 것 같습니다!

2024-01-23 08:36 UTC, SIWON990327 commented
이름 변경 및 트랜잭션 처리 완료했으며 API응답의 경우 외부 API가 IOExpection방식이라 sendemail과 checkemail은 Response의 Message를 파싱하여 리턴하게 하였습니다

2024-01-24 03:34 UTC, yeeunni approved these changes

2024-01-25 00:14 UTC, SIWON990327 commented
1. 폴더 구조를 맞췄습니다
2. 인터페이스와 구현체를 적용하였습니

2024-01-25 06:04 UTC, hig1002 approved these changes

2024-01-25 06:45 UTC, koojun99 approved these changes

2024-01-25 07:03 UTC, merged