[FIX]북마크 api 토큰 기반으로 수정
UMC-Umark/umark-server pull request #74
Opened 2024-02-18 01:49 UTC by hig1002

요청하신 url @SIZE 어노테이션 제거 했습니다.
북마크 좋아요, 신고 누르기
내가 좋아요 누른 북마크, 내가 쓴 북마크 조회 모두 토큰 기반으로 변경했습니다.

2024-02-18 03:07 UTC, koojun99 requested changes
수정해주신 api 엔드포인트들 SecurityConfig에서 토큰 검사 수행하도록 추가해주시면 감사드리겠습니다! 어려우시면 연락주세요!

2024-02-18 17:27 UTC, hig1002 commented
수정한 엔드포인트 SecurityConfig 에서 토큰 검사 하도록 엔드포인트 추가 하였습니다.

2024-02-19 08:21 UTC, yeeunni approved these changes

2024-02-19 09:01 UTC, koojun99 approved these changes

2024-02-20 04:24 UTC, merged